Add: channel visualization
aolabNeuro/analyze pull request #285
Opened 2022-04-22 04:24 UTC by m-nolan

multichannel data quality visualization code

2022-04-22 18:16 UTC, leoscholl commented on aopy/visualization.py
> +
docstrings needed for this and combine_channel_figures

2022-04-22 18:19 UTC, leoscholl requested changes
some test functions would be nice, you can make a couple of example figures from the fake ecube data, perhaps. and then combine them into a 2x1 grid. for `profile_data_channels` you can just call it with the same data and make sure there aren't any errors. you can also include one of the test figures into /docs/source/images, and use it place of the ------------- diagram in `plot_channel_summary`

2022-04-27 17:29 UTC, m-nolan commented
addressed the following:
- replaced the `advance_plot_color` function I accidentally deleted
- added tests for the channel plots
- added an example to the docs source image directory ('channel_profile_example.png')

2022-04-28 15:05 UTC, leoscholl approved these changes
i added some suggestions -- mainly filling in more of the docstrings, also changed the clim in the example, but not sure why nothing shows up in the ch2 spectrogram. looks good overall

2022-04-28 15:35 UTC, merged